/** Every string in the admin console, in one place. */
export const en = {
  app: { name: 'Nursery Link admin', shortName: 'Nursery Link', skipToContent: 'Skip to main content' },
  nav: {
    dashboard: 'Needs attention',
    insights: 'Insights',
    nurseries: 'Nurseries',
    inventory: 'Inventory',
    species: 'Species',
    news: 'News',
    deliveryRates: 'Delivery rates',
    campaigns: 'Campaigns',
    orders: 'Orders',
    toDispatch: 'new orders to dispatch',
    payouts: 'Payouts',
    serviceRequests: 'Service requests',
    feedback: 'Feedback',
    shadow: 'Nursery Shadow',
    audit: 'Audit log',
    signOut: 'Sign out',
    menu: 'Menu',
    closeMenu: 'Close menu',
    sections: { catalogue: 'Catalogue', money: 'Orders and money', analysis: 'Analysis' },
  },
  login: {
    title: 'Sign in',
    identifierLabel: 'Phone number or email',
    passwordLabel: 'Password',
    submit: 'Sign in',
    notAdmin: 'This account is not an administrator. Sign in with an admin account.',
    identifierRequired: 'Enter your phone number or email',
    passwordRequired: 'Enter your password',
  },
  states: {
    loadFailed: "We couldn't load this page.",
    retry: 'Try again',
    offline: "You're offline. Changes can't be saved until the connection is back.",
  },
  routeError: { title: 'Something went wrong on this page', body: 'The rest of the console still works. Try again.' },
  notFound: { title: 'No such page', body: 'Pick a section from the menu.' },
  common: {
    save: 'Save',
    saving: 'Saving…',
    saved: 'Saved',
    cancel: 'Cancel',
    create: 'Create',
    edit: 'Edit',
    delete: 'Delete',
    deleted: 'Deleted',
    add: 'Add',
    remove: 'Remove',
    search: 'Search',
    all: 'All',
    yes: 'Yes',
    no: 'No',
    back: 'Back',
    open: 'Open',
    retry: 'Try again',
    loadFailed: "We couldn't load this.",
    empty: 'Nothing here yet.',
    previous: 'Previous',
    next: 'Next',
    page: (n: number, of: number, total: number) => `Page ${String(n)} of ${String(of)} · ${String(total)} in total`,
    reasonLabel: 'Reason (kept in the audit log)',
    reasonHint: 'At least 5 characters, e.g. "Nursery confirmed by phone".',
    reasonTooShort: 'Write a reason of at least 5 characters.',
    confirmDelete: (what: string) => `Delete ${what}?`,
    confirmDeleteBody: 'This cannot be undone. If anything still uses it, you will be asked to deactivate it instead.',
    active: 'Active',
    inactive: 'Inactive',
    required: 'Required',
    changesSaved: 'Changes saved',
    scrollTable: 'Table (scroll sideways to see every column)',

  },
  dashboard: {
    title: 'Needs attention',
    intro: 'Work through these lists; each item links to where you can fix it.',
    greeting: (name: string) => `Oli otya, ${name}`,
    greetingMeaning: '"How are you?" in Luganda',
    seeInsights: 'See the numbers',
    allClear: 'Nothing waiting. Well done.',
    disputed: 'Disputed orders',
    disputedHelp: 'The nursery reported a problem, or the buyer did. Decide: dispatch, refund or release.',
    stuck: (h: number) => `Paid, not dispatched after ${String(h)} hours`,
    stuckHelp: 'Call the nursery to check they received the order SMS.',
    failedPayouts: 'Failed payouts',
    failedPayoutsHelp: 'Money we could not send. Check the number, then retry.',
    staleStock: (d: number) => `Stock not updated in ${String(d)} days`,
    staleStockHelp: 'Call the nursery and update its stock.',
    toDispatch: 'New orders to dispatch',
    toDispatchHelp: 'Paid (or confirmed in trial mode). The nursery has the SMS: mark each dispatched once they confirm the seedlings have left.',
    toVerify: 'Imported nurseries to verify',
    toVerifyHelp: 'Phone each one, correct its details and location, add stock, then tick “Listed on the site”.',
    pendingApps: 'Free-seedling applications to review',
    pendingAppsHelp: 'Approve or reject; approval takes seedlings from the campaign.',
    unparsedSms: (d: number) => `SMS replies we couldn't read (last ${String(d)} days)`,
    unparsedSmsHelp: 'Read them and act on the order by hand if needed.',
    viewAll: 'View all',
    attempts: (n: number) => `${String(n)} attempts`,
    neverUpdated: 'Never',
  },
  nurseries: {
    nurseryPin: 'Nursery location (drag to move)',
    title: 'Nurseries',
    new: 'Add nursery',
    editTitle: (name: string) => `Edit ${name}`,
    newTitle: 'Add a nursery',
    searchPlaceholder: 'Search by name',
    columns: { name: 'Name', place: 'Sub-county', type: 'Type', cert: 'Certification', stock: 'Stock updated', status: 'Status' },
    name: 'Nursery name',
    type: 'Type',
    types: { private: 'Private', commercial: 'Commercial', community: 'Community' },
    operator: 'Operator name',
    contactPhone: 'Contact phone (receives order SMS)',
    payoutPhone: 'Payout phone (receives mobile money)',
    capacity: 'Annual capacity (seedlings)',
    seedSource: 'Seed source',
    certification: 'Certification',
    certs: { certified: 'Certified', pending: 'Pending', unverified: 'Not verified' },
    active: 'Listed on the site',
    location: 'Location',
    locationHelp: 'Click the map to place the nursery, drag the pin, or paste coordinates. The sub-county and district are set from the point.',
    coordinates: 'Coordinates (lat, lng)',
    coordinatesHint: 'e.g. 0.3533, 32.7553',
    coordinatesInvalid: 'Paste latitude and longitude, e.g. 0.3533, 32.7553',
    zoomTo: 'Zoom the map to',
    district: 'District',
    subCounty: 'Sub-county',
    derived: (sub: string, district: string) => `Placed in ${sub}, ${district}`,
    pickLocation: 'Place the nursery on the map.',
    inventory: 'Edit stock',
    created: 'Nursery added',
    sample: 'Sample',
    toVerify: 'To verify',
    show: 'Show',
    showReal: 'Real nurseries',
    showDemo: 'Sample nurseries',
    sampleNote: 'Sample nursery: invented for testing (db:demo-nurseries). It is never texted and can’t take real orders. Edits are overwritten when the sample data is reloaded.',
    importNoteTitle: 'Imported: check before listing',
  },
  inventory: {
    title: 'Inventory',
    chooseNursery: 'Nursery',
    pickNursery: 'Choose a nursery to edit its stock',
    columns: { species: 'Tree', quantity: 'Quantity', price: 'Price (UGX)', updated: 'Updated' },
    addLine: 'Add a tree',
    species: 'Tree',
    quantity: 'Quantity available',
    price: 'Price each (UGX)',
    rowSaved: (name: string) => `${name} saved`,
    importTitle: 'Import from CSV',
    importIntro: 'Upload a CSV to update many stock lines at once. You see a preview first; nothing changes until you commit.',
    template: 'Download the template',
    chooseFile: 'Choose a CSV file',
    preview: 'Check the file',
    commit: (n: number) => (n === 1 ? 'Apply 1 change' : `Apply ${String(n)} changes`),
    previewHeading: 'Preview',
    summary: (c: number, u: number, s: number) => `${String(c)} new · ${String(u)} changed · ${String(s)} unchanged`,
    rowErrors: (n: number) => `${n === 1 ? '1 row has a problem' : `${String(n)} rows have problems`}. Fix the file and check it again; nothing has been applied.`,
    row: 'Row',
    action: 'Change',
    actions: { create: 'New', update: 'Changed', unchanged: 'Same' },
    before: 'Before',
    after: 'After',
    problem: 'Problem',
    committed: (n: number) => (n === 1 ? '1 stock line updated' : `${String(n)} stock lines updated`),
    nothingToApply: 'Nothing to change: the file matches the current stock.',
  },
  species: {
    title: 'Species',
    new: 'Add species',
    newTitle: 'Add a species',
    editTitle: (name: string) => `Edit ${name}`,
    searchPlaceholder: 'Search by name',
    columns: { name: 'Common name', scientific: 'Scientific name', category: 'Category', nurseries: 'Nurseries' },
    commonName: 'Common name',
    scientificName: 'Scientific name',
    slug: 'Web address (slug)',
    slugHint: 'Leave empty to make one from the common name.',
    category: 'Category',
    categories: { indigenous: 'Indigenous', agroforestry: 'Agroforestry', exotic: 'Exotic', ornamental: 'Ornamental', medicinal: 'Medicinal', coffee: 'Coffee', cocoa: 'Cocoa' },
    pace: 'Growth pace',
    paces: { fast: 'Fast', moderate: 'Moderate', slow: 'Slow' },
    timeline: 'Height over the years',
    years: 'Years',
    height: 'Height (m)',
    heightUnit: 'm tall',
    canopy: 'Canopy notes',
    roots: 'Root notes',
    zones: 'Ecological zones',
    zonesHint: 'One per line',
    localNames: 'Local names',
    language: 'Language',
    localName: 'Name',
    media: 'Photos',
    caption: 'Caption and credit',
    upload: 'Upload a photo',
    uploading: 'Uploading…',
    uploaded: 'Photo uploaded',
    created: 'Species added',
  },
  news: {
    title: 'News',
    new: 'Write a post',
    newTitle: 'Write a post',
    editTitle: 'Edit post',
    columns: { title: 'Title', category: 'Category', status: 'Status', date: 'Date' },
    postTitle: 'Title',
    category: 'Category',
    categories: { weather: 'Weather', market: 'Market prices', policy: 'Policy', grant: 'Grants' },
    body: 'Article (Markdown)',
    bodyHint: '## for a heading, **bold**, - for a list, [text](https://link) for a link.',
    preview: 'Preview',
    write: 'Write',
    cover: 'Cover photo URL (optional)',
    publish: 'Published on the site',
    publishAt: 'Publish date (optional: a future date schedules it)',
    draft: 'Draft',
    published: 'Published',
    scheduled: 'Scheduled',
    created: 'Post saved',
  },
  rates: {
    title: 'Delivery rates',
    intro: 'Quotes use the cheapest active rate that can carry the order. Fee = base + per km × road kilometres.',
    columns: { vehicle: 'Vehicle', maxItems: 'Up to (seedlings)', base: 'Base fee', perKm: 'Per km', maxKm: 'Up to (km)', active: 'Active' },
    vehicles: { motorcycle: 'Motorcycle (boda)', truck: 'Truck' },
    add: 'Add a rate',
    example: (fee: string) => `e.g. 10 km costs ${fee}`,
  },
  campaigns: {
    title: 'Campaigns',
    new: 'New campaign',
    newTitle: 'New campaign',
    editTitle: (t: string) => `Edit ${t}`,
    columns: { title: 'Campaign', sub: 'Sub-county', stock: 'Left', dates: 'Runs', status: 'Status' },
    open: 'Open',
    closed: 'Closed',
    campaignTitle: 'Title',
    funderName: 'Funder',
    funderType: 'Funder type',
    funderTypes: { government: 'Government', ngo: 'NGO', foundation: 'Foundation', corporate: 'Company' },
    purpose: 'Purpose',
    pickup: 'Pickup nursery',
    subCounty: 'Sub-county served',
    starts: 'Starts',
    ends: 'Ends',
    active: 'Switched on',
    items: 'Seedlings allocated',
    addItem: 'Add a tree',
    allocated: (n: string) => `${n} seedlings in total`,
    rules: 'Who can apply (eligibility rules)',
    rulesHelp: 'Each rule becomes a question on the application form. A required yes/no question must be answered "yes".',
    addRule: 'Add a rule',
    ruleLabel: 'Question shown to applicants',
    ruleType: 'Answer type',
    ruleTypes: { boolean: 'Yes / no', number: 'Number', text: 'Text' },
    ruleRequired: 'Required',
    previewHeading: 'What applicants will see',
    previewNote: 'Live preview; submitting here does nothing.',
    applications: 'Applications',
    created: 'Campaign saved',
  },
  serviceRequests: {
    title: 'Service requests',
    intro: 'Buyers asking for planting help from the Services page. Phone them back, agree the work and the price, then record what happened.',
    columns: { requester: 'Who asked', service: 'Service', where: 'Where', notes: 'Notes', date: 'Asked', status: 'Status', note: 'Our note' },
    services: { farm_plan: 'Farm or woodlot plan', site_visit: 'Site visit and soil check', planting: 'Planting crew', watering: 'Watering and aftercare', orchard_care: 'Fruit orchard care', survival_check: 'Survival check', training: 'Training' },
    statuses: { new: 'New', contacted: 'Contacted', scheduled: 'Scheduled', done: 'Done', cancelled: 'Cancelled' },
    actions: { contacted: 'Contacted', scheduled: 'Scheduled', done: 'Done', cancelled: 'Cancel' },
    toast: (status: string) => `Marked ${status.toLowerCase()}`,
    acres: (n: string) => `${n} acres`,
    noteLabel: 'Note for the buyer (optional), e.g. the agreed date and price',
    status: 'Status',
    service: 'Service',
    allServices: 'All services',
  },
  feedback: {
    title: 'Feedback',
    intro: 'Messages from people using the public site (its Feedback page). Mark them read, and done once acted on.',
    columns: { kind: 'About', message: 'Message', from: 'From', page: 'Page', date: 'Sent', status: 'Status', note: 'Our note' },
    kinds: { experience: 'Experience', suggestion: 'Suggestion', problem: 'Problem' },
    statuses: { new: 'New', read: 'Read', done: 'Done' },
    anonymous: 'Anonymous',
    account: 'Signed-in buyer',
    markRead: 'Mark read',
    markDone: 'Done',
    reopen: 'Reopen',
    doneTitle: 'Mark this feedback done',
    noteLabel: 'Note for the team (optional), e.g. what was changed',
    toast: (status: string) => `Marked ${status.toLowerCase()}`,
    status: 'Status',
    kind: 'About',
    allKinds: 'Everything',
  },
  applications: {
    title: (c: string) => `Applications: ${c}`,
    remaining: (n: string) => `${n} seedlings left in this campaign`,
    columns: { applicant: 'Applicant', answers: 'Answers', quantity: 'Asks for', status: 'Status', date: 'Applied' },
    statuses: { pending: 'Pending', approved: 'Approved', rejected: 'Rejected', collected: 'Collected' },
    approve: 'Approve',
    reject: 'Reject',
    collected: 'Mark collected',
    notEnough: 'Not enough seedlings left',
    approvedToast: 'Approved. The applicant gets an SMS.',
    rejectedToast: 'Rejected. The applicant gets an SMS.',
    collectedToast: 'Marked as collected.',
    noteLabel: 'Note (optional, kept in the audit log)',
  },
  orders: {
    trialConfirmed: 'Confirmed (trial, no payment)',
    title: 'Orders',
    status: 'Status',
    allStatuses: 'All statuses',
    columns: { code: 'Order', buyer: 'Buyer', nursery: 'Nursery', total: 'Total', status: 'Status', date: 'Ordered' },
    searchPlaceholder: 'Order code, buyer name or phone',
    allFromBuyer: 'All orders from this buyer',
    allFromNursery: 'All orders from this nursery',
    nurseryFilter: (name: string | null) => (name ? `Nursery: ${name}` : 'One nursery'),
    buyerFilter: (name: string | null) => (name ? `Buyer: ${name}` : 'One buyer'),
    clearFilter: 'Remove this filter',
    nurseryOrders: 'Orders',
    statuses: {
      pending_payment: 'Waiting for payment',
      escrow_held: 'Paid, held',
      dispatched: 'Dispatched',
      delivered: 'Delivered',
      released: 'Completed',
      disputed: 'Disputed',
      refunded: 'Refunded',
      cancelled: 'Cancelled',
    },
    detailTitle: (code: string) => `Order ${code}`,
    buyer: 'Buyer',
    nursery: 'Nursery',
    payment: 'Payment',
    items: 'Items',
    delivery: 'Delivery',
    collect: 'Buyer collects',
    actions: 'Actions',
    noActions: 'No actions: this order is finished or waiting for payment.',
    action: {
      dispatched: 'Mark dispatched',
      refunded: 'Refund the buyer',
      released: 'Release payment to the nursery',
    },
    actionHelp: {
      dispatched: 'Use when the nursery confirms by phone that the seedlings have left.',
      refunded: 'Sends the paid amount back to the number that paid. The order is marked disputed until the refund succeeds.',
      released: 'Pays the nursery. Use when the buyer confirms receipt by phone.',
    },
    actionDone: 'Done. The order will update as soon as the payment provider confirms.',
    history: 'History',
    by: (name: string) => `by ${name}`,
    system: 'automatic',
  },
  payouts: {
    title: 'Payouts',
    intro: 'Money sent to nurseries (disbursements) and back to buyers (refunds).',
    status: 'Status',
    columns: { order: 'Order', kind: 'Type', to: 'To', amount: 'Amount', status: 'Status', attempts: 'Attempts', updated: 'Updated' },
    kinds: { disbursement: 'To nursery', refund: 'Refund to buyer', collection: 'Collection' },
    statuses: { pending: 'Pending', successful: 'Sent', failed: 'Failed' },
    retry: 'Retry',
    retried: 'Retry started',
  },
  audit: {
    title: 'Audit log',
    intro: 'Every admin change and every order or payment step, newest first. Entries cannot be edited or deleted.',
    entity: 'Record type',
    action: 'Action contains',
    from: 'From',
    to: 'To',
    columns: { when: 'When', who: 'Who', action: 'Action', record: 'Record' },
    system: 'System',
    before: 'Before',
    after: 'After',
    noChange: 'No details recorded',
    showDiff: 'Show changes',
  },
  shadow: {
    title: 'Nursery Shadow',
    intro: 'Places losing forest that are more than 20 km by road from every nursery: where a new nursery, or a campaign, would help most.',
    paramsHeading: 'Run the analysis',
    threshold: 'Forest lost (at least, %)',
    thresholdHint: 'Share of a 1 km square cleared since the year below.',
    sinceYear: 'Counting loss since',
    sinceYearHint: (first: number) => `${String(first)} or later (the satellite record starts in ${String(first)}).`,
    run: 'Run analysis',
    outcome: {
      new: 'Started. This takes a minute or two; the map appears when it finishes.',
      in_progress: 'Already running with these settings; showing that run.',
      cached: 'Nothing has changed since the last run with these settings; showing it.',
    },
    runs: 'Earlier runs',
    noRuns: 'No runs yet. Choose the settings and run the analysis.',
    statuses: { queued: 'Waiting', running: 'Running', succeeded: 'Done', failed: 'Failed' },
    runLabel: (pct: number, year: number) => `≥ ${String(pct)}% since ${String(year)}`,
    started: (when: string) => `Started ${when}`,
    failed: (reason: string) => `This run failed: ${reason}`,
    working: 'Measuring every nursery’s reach by road and comparing it with forest loss…',
    summary: (zones: number, km2: string, nurseries: number) =>
      `${String(zones)} shadow ${zones === 1 ? 'zone' : 'zones'} · ${km2} km² · ${String(nurseries)} ${nurseries === 1 ? 'nursery' : 'nurseries'} measured`,
    zoneCount: (n: number) => (n === 1 ? '1 zone' : `${String(n)} zones`),
    noShadows: 'No shadow zones: every place losing this much forest is within 20 km of a nursery.',
    layers: 'Map layers',
    layer: {
      cells: 'Forest loss (1 km squares)',
      shadows: 'Shadow zones',
      zones: 'Nursery reach (5, 10, 20 km by road)',
      nurseries: 'Nurseries',
    },
    legend: {
      lossLow: (pct: number) => `${String(pct)}% lost`,
      lossHigh: '100% lost',
      inShadow: 'Square inside a shadow zone',
      shadow: 'Shadow zone',
      reach: '20 km reach',
      nursery: 'Nursery',
    },
    mapLabel: 'Map of forest loss, nursery reach and shadow zones',
    zonesHeading: 'Shadow zones, largest first',
    columns: { rank: '#', district: 'District', area: 'Area', loss: 'Forest lost', show: '' },
    show: 'Show on map',
    unknownDistrict: 'Outside the districts',
    km2: (n: string) => `${n} km²`,
    pct: (n: string) => `${n}%`,
    export: 'Download GeoJSON',
    exported: 'Download started',
    dataSource: 'Forest-loss data',
    dataLoaded: (rows: string, when: string, sources: string) => `${rows} cell-years loaded ${when} from ${sources}.`,
    noData: 'No forest-loss data is loaded, so no shadows can be found. Load it with scripts/forest-loss (see its README).',
    sampleWarning: 'This is invented sample data for development, not real satellite data. Do not use these results for decisions.',
    cellPopup: (pct: string, inShadow: boolean) => `${pct}% of this square lost${inShadow ? ' · in a shadow zone' : ''}`,
    zonePopup: (km2: string, pct: string, district: string) => `Shadow zone · ${km2} km² · ${pct}% lost · ${district}`,
    reachPopup: (name: string, km: number) => `${name}: within ${String(km)} km by road`,
  },
  insights: {
    title: 'Insights',
    intro: 'How the marketplace is doing: sales, what people buy, where, and how they pay. Sales are paid orders that were not refunded.',
    range: 'Period',
    ranges: { '30d': 'Last 30 days', '90d': 'Last 90 days', '12m': 'Last 12 months' },
    vsPrevious: { '30d': 'vs the 30 days before', '90d': 'vs the 90 days before', '12m': 'vs the year before' },
    kpis: {
      sales_ugx: 'Sales',
      orders: 'Paid orders',
      seedlings_sold: 'Seedlings sold',
      avg_order_ugx: 'Average order',
      new_buyers: 'New buyers',
      free_seedlings: 'Free seedlings approved',
    },
    noChange: 'No change',
    newValue: 'New',
    salesOverTime: 'Sales over time',
    show: 'Show',
    metric: { sales: 'Sales (UGX)', orders: 'Orders' },
    orderStatus: 'Orders by status',
    orderStatusHint: 'Every order placed in the period, by where it is now',
    delivery: 'Delivery or collection',
    paymentMethods: 'How buyers pay',
    topSpecies: 'Best-selling trees',
    topSpeciesUnit: (n: string) => `${n} seedlings`,
    topNurseries: 'Top nurseries by sales',
    topNurseriesOrders: (n: number) => `${String(n)} ${n === 1 ? 'order' : 'orders'}`,
    stock: 'Seedlings in stock now',
    stockHint: 'At active nurseries, by kind of tree',
    campaigns: 'Free-seedling campaigns',
    campaignGiven: (given: string, total: string) => `${given} of ${total} given out`,
    campaignApplications: (n: number) => `${String(n)} ${n === 1 ? 'application' : 'applications'}`,
    total: 'Total',
    units: { orders: 'orders', seedlings: 'seedlings' },
    empty: 'No sales in this period yet.',
    emptyShort: 'Nothing yet',
    chartTable: 'Figures behind the chart',
    columns: { period: 'Period', sales: 'Sales', orders: 'Orders' },
    deliveryTypes: { order_and_deliver: 'Delivered', self_pickup: 'Collected' },
    methods: { mtn_momo: 'MTN MoMo', airtel_money: 'Airtel Money', trial: 'No payment (trial)' },
  },
} as const;

