import type { GrowthPace, SpeciesCategory } from '@nurserylink/shared';

export interface SeedSpecies {
  slug: string;
  scientificName: string;
  commonName: string;
  category: SpeciesCategory;
  growthPace: GrowthPace;
  heightTimeline: { years: number; height_m: number }[];
  canopyNotes: string;
  rootNotes: string;
  ecologicalZones: string[];
  /** Only names we are confident of; more can be added by admins */
  localNames: { language: string; name: string }[];
  /** Photos served by apps/web from public/images (Wikimedia Commons; credit in the caption) */
  media: { url: string; caption: string }[];
}

/**
 * National Forestry Authority prices (price list of assorted tree seedlings, January 2024, docs/),
 * for the smallest pot NFA lists: [UGX per seedling, pot size in inches]. Bottlebrush isn't listed.
 * Mango and avocado are NFA's grafted prices (Hass for avocado); eucalyptus is local E. grandis.
 */
export const NFA_PRICES: Record<string, [number, number]> = {
  mvule: [500, 3],
  musizi: [500, 3],
  nsambya: [500, 3],
  mukebu: [700, 3],
  'african-mahogany': [500, 3],
  mutuba: [1000, 5],
  grevillea: [300, 3],
  calliandra: [300, 3],
  mugavu: [500, 3],
  jackfruit: [1500, 5],
  'hass-avocado': [5000, 5],
  mango: [3000, 5],
  'eucalyptus-grandis': [200, 3],
  'caribbean-pine': [500, 3],
  teak: [500, 3],
  jacaranda: [500, 3],
  'nandi-flame': [500, 3],
  'prunus-africana': [500, 3],
  neem: [500, 3],
  moringa: [400, 3],
};

const LAKE = 'Lake Victoria Crescent';
const MOIST = 'Moist forest';
const WETLAND = 'Wetland margins';
const FARMLAND = 'Farmland and homesteads';
const HIGHLAND = 'Highlands';
const DRY = 'Dry savanna';

export const SPECIES: SeedSpecies[] = [
  // ── Indigenous ───────────────────────────────────────────
  {
    slug: 'mvule',
    scientificName: 'Milicia excelsa',
    commonName: 'Mvule',
    category: 'indigenous',
    growthPace: 'slow',
    heightTimeline: [{ years: 1, height_m: 1 }, { years: 5, height_m: 6 }, { years: 15, height_m: 18 }, { years: 40, height_m: 35 }],
    canopyNotes: 'Broad, spreading crown casting deep shade when mature.',
    rootNotes: 'Deep taproot with wide lateral roots; plant at least 10 m from buildings.',
    ecologicalZones: [LAKE, MOIST, FARMLAND],
    localNames: [{ language: 'Luganda', name: 'Muvule' }],
    media: [{ url: '/images/sp-mvule.jpg', caption: 'Mvule trees by a road in Manafwa District. Photo: Fenrith, CC BY 3.0' }],
  },
  {
    slug: 'musizi',
    scientificName: 'Maesopsis eminii',
    commonName: 'Musizi',
    category: 'indigenous',
    growthPace: 'fast',
    heightTimeline: [{ years: 1, height_m: 2 }, { years: 5, height_m: 12 }, { years: 15, height_m: 25 }],
    canopyNotes: 'Light, open crown; widely used as shade for coffee and bananas.',
    rootNotes: 'Moderately deep roots; competes little with crops once established.',
    ecologicalZones: [LAKE, MOIST, FARMLAND],
    localNames: [{ language: 'Luganda', name: 'Musizi' }],
    media: [{ url: '/images/sp-musizi.jpg', caption: 'Maesopsis eminii. Photo: Gerard D. Hertel, Bugwood.org, CC BY 3.0 US' }],
  },
  {
    slug: 'nsambya',
    scientificName: 'Markhamia lutea',
    commonName: 'Nsambya',
    category: 'indigenous',
    growthPace: 'moderate',
    heightTimeline: [{ years: 1, height_m: 1.5 }, { years: 5, height_m: 7 }, { years: 15, height_m: 15 }],
    canopyNotes: 'Narrow, upright crown with light shade; crops grow well beneath it.',
    rootNotes: 'Deep roots; good for boundaries and windbreaks. Coppices after cutting.',
    ecologicalZones: [LAKE, FARMLAND, HIGHLAND],
    localNames: [{ language: 'Luganda', name: 'Nsambya' }],
    media: [{ url: '/images/sp-nsambya.jpg', caption: 'Markhamia lutea. Photo: Dube2022, CC BY-SA 4.0' }],
  },
  {
    slug: 'mukebu',
    scientificName: 'Cordia africana',
    commonName: 'Mukebu',
    category: 'indigenous',
    growthPace: 'moderate',
    heightTimeline: [{ years: 1, height_m: 1.5 }, { years: 5, height_m: 6 }, { years: 15, height_m: 12 }],
    canopyNotes: 'Rounded crown; white flowers much visited by bees.',
    rootNotes: 'Moderately deep roots; suitable among coffee at 8–10 m spacing.',
    ecologicalZones: [LAKE, FARMLAND],
    localNames: [{ language: 'Luganda', name: 'Mukebu' }],
    media: [{ url: '/images/sp-mukebu.jpg', caption: 'Cordia africana foliage. Photo: Sue Christian Bell, CC BY-SA 3.0' }],
  },
  {
    slug: 'african-mahogany',
    scientificName: 'Khaya anthotheca',
    commonName: 'African mahogany',
    category: 'indigenous',
    growthPace: 'slow',
    heightTimeline: [{ years: 1, height_m: 0.8 }, { years: 5, height_m: 5 }, { years: 20, height_m: 20 }, { years: 40, height_m: 35 }],
    canopyNotes: 'Large, dense crown; best planted among other trees or on forest edges.',
    rootNotes: 'Deep, extensive roots; prefers moist, deep soils and riverbanks.',
    ecologicalZones: [MOIST, WETLAND],
    localNames: [],
    media: [{ url: '/images/sp-mahogany.jpg', caption: 'Khaya anthotheca. Photo: Andrew Massyn, public domain' }],
  },
  {
    slug: 'mutuba',
    scientificName: 'Ficus natalensis',
    commonName: 'Mutuba (barkcloth fig)',
    category: 'indigenous',
    growthPace: 'fast',
    heightTimeline: [{ years: 1, height_m: 2 }, { years: 5, height_m: 6 }, { years: 15, height_m: 12 }],
    canopyNotes: 'Dense evergreen crown; traditional boundary and shade tree.',
    rootNotes: 'Grown from large cuttings; roots quickly at the start of the rains.',
    ecologicalZones: [LAKE, FARMLAND],
    localNames: [{ language: 'Luganda', name: 'Mutuba' }],
    media: [{ url: '/images/sp-mutuba.jpg', caption: 'Stripping Mutuba bark for barkcloth. Photo: Joyce Nanjobe Kawooya, CC BY-SA 4.0' }],
  },

  // ── Agroforestry ─────────────────────────────────────────
  {
    slug: 'grevillea',
    scientificName: 'Grevillea robusta',
    commonName: 'Grevillea',
    category: 'agroforestry',
    growthPace: 'fast',
    heightTimeline: [{ years: 1, height_m: 1.5 }, { years: 5, height_m: 8 }, { years: 15, height_m: 20 }],
    canopyNotes: 'Narrow crown that can be pruned for firewood; light shade for coffee and tea.',
    rootNotes: 'Deep roots that compete little with crops; good on contours and boundaries.',
    ecologicalZones: [FARMLAND, HIGHLAND],
    localNames: [],
    media: [{ url: '/images/sp-grevillea.jpg', caption: 'Grevillea robusta. Photo: MarioM, CC BY-SA 3.0' }],
  },
  {
    slug: 'calliandra',
    scientificName: 'Calliandra calothyrsus',
    commonName: 'Calliandra',
    category: 'agroforestry',
    growthPace: 'fast',
    heightTimeline: [{ years: 1, height_m: 2 }, { years: 3, height_m: 4 }, { years: 6, height_m: 6 }],
    canopyNotes: 'Shrubby, multi-stemmed; cut regularly for fodder hedges.',
    rootNotes: 'Fixes nitrogen and improves soil; roots hold contour bunds.',
    ecologicalZones: [FARMLAND, HIGHLAND],
    localNames: [],
    media: [],
  },
  {
    slug: 'mugavu',
    scientificName: 'Albizia coriaria',
    commonName: 'Mugavu',
    category: 'agroforestry',
    growthPace: 'moderate',
    heightTimeline: [{ years: 1, height_m: 1.2 }, { years: 5, height_m: 7 }, { years: 15, height_m: 15 }],
    canopyNotes: 'Flat, spreading crown giving dappled shade; common coffee shade tree.',
    rootNotes: 'Nitrogen-fixing; deep roots.',
    ecologicalZones: [LAKE, FARMLAND],
    localNames: [{ language: 'Luganda', name: 'Mugavu' }],
    media: [],
  },
  {
    slug: 'jackfruit',
    scientificName: 'Artocarpus heterophyllus',
    commonName: 'Jackfruit',
    category: 'agroforestry',
    growthPace: 'moderate',
    heightTimeline: [{ years: 1, height_m: 1 }, { years: 4, height_m: 4 }, { years: 10, height_m: 10 }],
    canopyNotes: 'Dense evergreen crown; fruits within 3–5 years.',
    rootNotes: 'Deep taproot; keep at least 8 m from buildings.',
    ecologicalZones: [LAKE, FARMLAND],
    localNames: [{ language: 'Luganda', name: 'Ffene' }],
    media: [{ url: '/images/sp-jackfruit.jpg', caption: 'Ugandan jackfruit on the tree. Photo: Denis Kasozi, CC BY 4.0' }],
  },
  {
    slug: 'hass-avocado',
    scientificName: 'Persea americana',
    commonName: 'Hass avocado (grafted)',
    category: 'agroforestry',
    growthPace: 'moderate',
    heightTimeline: [{ years: 1, height_m: 1 }, { years: 3, height_m: 3 }, { years: 8, height_m: 7 }],
    canopyNotes: 'Rounded crown; grafted trees fruit in 2–3 years.',
    rootNotes: 'Shallow feeder roots; needs well-drained soil and does not tolerate waterlogging.',
    ecologicalZones: [FARMLAND, HIGHLAND],
    localNames: [{ language: 'Luganda', name: 'Ovakedo' }],
    media: [{ url: '/images/sp-avocado.jpg', caption: 'Avocados on a tree in Uganda. Photo: Denis Kasozi, CC BY-SA 4.0' }],
  },
  {
    slug: 'mango',
    scientificName: 'Mangifera indica',
    commonName: 'Mango (grafted)',
    category: 'agroforestry',
    growthPace: 'moderate',
    heightTimeline: [{ years: 1, height_m: 1 }, { years: 4, height_m: 4 }, { years: 10, height_m: 9 }],
    canopyNotes: 'Wide, dense crown; plant 8–10 m apart.',
    rootNotes: 'Deep taproot; drought tolerant once established.',
    ecologicalZones: [FARMLAND, DRY],
    localNames: [{ language: 'Luganda', name: 'Muyembe' }],
    media: [{ url: '/images/sp-mango.jpg', caption: 'A mango ripening on the tree. Photo: safaritravelplus, CC0' }],
  },

  // ── Exotic ───────────────────────────────────────────────
  {
    slug: 'eucalyptus-grandis',
    scientificName: 'Eucalyptus grandis',
    commonName: 'Eucalyptus',
    category: 'exotic',
    growthPace: 'fast',
    heightTimeline: [{ years: 1, height_m: 3 }, { years: 5, height_m: 18 }, { years: 10, height_m: 30 }],
    canopyNotes: 'Tall, narrow crown; grown in woodlots for poles and firewood.',
    rootNotes: 'Aggressive, water-hungry roots; keep away from wetlands, springs and food gardens.',
    ecologicalZones: [FARMLAND, HIGHLAND],
    localNames: [{ language: 'Luganda', name: 'Kalitunsi' }],
    media: [{ url: '/images/sp-eucalyptus.jpg', caption: 'Eucalyptus plantation in Sonde, Mukono District. Photo: Emma Oruk, CC BY-SA 4.0' }],
  },
  {
    slug: 'caribbean-pine',
    scientificName: 'Pinus caribaea',
    commonName: 'Caribbean pine',
    category: 'exotic',
    growthPace: 'fast',
    heightTimeline: [{ years: 1, height_m: 1 }, { years: 5, height_m: 8 }, { years: 20, height_m: 25 }],
    canopyNotes: 'Conical crown; plantation softwood for sawn timber.',
    rootNotes: 'Deep taproot; create firebreaks around plantations before the dry season.',
    ecologicalZones: [FARMLAND],
    localNames: [],
    media: [{ url: '/images/sp-pine.jpg', caption: 'Pinus caribaea. Photo: Krzysztof Ziarnek, Kenraiz, CC BY-SA 4.0' }],
  },
  {
    slug: 'teak',
    scientificName: 'Tectona grandis',
    commonName: 'Teak',
    category: 'exotic',
    growthPace: 'moderate',
    heightTimeline: [{ years: 1, height_m: 1.5 }, { years: 5, height_m: 9 }, { years: 20, height_m: 25 }],
    canopyNotes: 'Large leaves, deciduous in the dry season.',
    rootNotes: 'Needs deep, well-drained soil; does poorly in waterlogged ground.',
    ecologicalZones: [FARMLAND, DRY],
    localNames: [],
    media: [],
  },

  // ── Ornamental ───────────────────────────────────────────
  {
    slug: 'jacaranda',
    scientificName: 'Jacaranda mimosifolia',
    commonName: 'Jacaranda',
    category: 'ornamental',
    growthPace: 'moderate',
    heightTimeline: [{ years: 1, height_m: 1.5 }, { years: 5, height_m: 6 }, { years: 15, height_m: 12 }],
    canopyNotes: 'Spreading crown with purple flowers; popular for avenues and compounds.',
    rootNotes: 'Moderately deep; can lift paving if planted too close.',
    ecologicalZones: [FARMLAND, HIGHLAND],
    localNames: [],
    media: [],
  },
  {
    slug: 'nandi-flame',
    scientificName: 'Spathodea campanulata',
    commonName: 'Nandi flame',
    category: 'ornamental',
    growthPace: 'fast',
    heightTimeline: [{ years: 1, height_m: 2 }, { years: 5, height_m: 8 }, { years: 15, height_m: 15 }],
    canopyNotes: 'Dense crown with bright orange-red flowers.',
    rootNotes: 'Shallow to moderate roots; brittle branches, so keep away from houses.',
    ecologicalZones: [LAKE, MOIST],
    localNames: [{ language: 'Luganda', name: 'Kifabakazi' }],
    media: [],
  },
  {
    slug: 'bottlebrush',
    scientificName: 'Callistemon citrinus',
    commonName: 'Bottlebrush',
    category: 'ornamental',
    growthPace: 'moderate',
    heightTimeline: [{ years: 1, height_m: 1 }, { years: 3, height_m: 2.5 }, { years: 8, height_m: 5 }],
    canopyNotes: 'Small tree or large shrub with red brush-like flowers; attracts sunbirds.',
    rootNotes: 'Compact roots; suitable near buildings and along drives.',
    ecologicalZones: [FARMLAND, WETLAND],
    localNames: [],
    media: [],
  },

  // ── Medicinal ────────────────────────────────────────────
  {
    slug: 'prunus-africana',
    scientificName: 'Prunus africana',
    commonName: 'African cherry',
    category: 'medicinal',
    growthPace: 'moderate',
    heightTimeline: [{ years: 1, height_m: 1 }, { years: 5, height_m: 6 }, { years: 20, height_m: 20 }],
    canopyNotes: 'Dense evergreen crown; bark used in medicine and over-harvested in the wild.',
    rootNotes: 'Deep roots that protect steep slopes.',
    ecologicalZones: [HIGHLAND, MOIST],
    localNames: [],
    media: [{ url: '/images/sp-prunus.jpg', caption: "Prunus africana in Kibira National Park. Photo: Kubwimana Bienvenu, CC BY-SA 4.0" }],
  },
  {
    slug: 'neem',
    scientificName: 'Azadirachta indica',
    commonName: 'Neem',
    category: 'medicinal',
    growthPace: 'fast',
    heightTimeline: [{ years: 1, height_m: 1.5 }, { years: 5, height_m: 7 }, { years: 15, height_m: 15 }],
    canopyNotes: 'Dense crown; leaves and seeds used as natural pest repellent.',
    rootNotes: 'Deep taproot; very drought tolerant.',
    ecologicalZones: [DRY, FARMLAND],
    localNames: [],
    media: [],
  },
  {
    slug: 'moringa',
    scientificName: 'Moringa oleifera',
    commonName: 'Moringa',
    category: 'medicinal',
    growthPace: 'fast',
    heightTimeline: [{ years: 1, height_m: 3 }, { years: 3, height_m: 6 }, { years: 6, height_m: 9 }],
    canopyNotes: 'Open, feathery crown; leaves eaten as a nutritious vegetable.',
    rootNotes: 'Thick taproot; tolerates poor soils. Cut back yearly to keep leaves in reach.',
    ecologicalZones: [DRY, FARMLAND],
    localNames: [],
    media: [],
  },

  // ── Coffee ───────────────────────────────────────────────
  {
    slug: 'robusta-coffee',
    scientificName: 'Coffea canephora',
    commonName: 'Robusta coffee',
    category: 'coffee',
    growthPace: 'moderate',
    heightTimeline: [{ years: 1, height_m: 0.6 }, { years: 3, height_m: 2 }, { years: 6, height_m: 3.5 }],
    canopyNotes: 'Bushy shrub, usually pruned to 2–3 m; first crop after about 2–3 years. Plant 3 m apart, with light shade.',
    rootNotes: 'Shallow feeder roots; mulch well and keep weeds away. Ask for clonal (wilt-resistant) seedlings.',
    ecologicalZones: [LAKE, FARMLAND, MOIST],
    localNames: [{ language: 'Luganda', name: 'Mmwanyi' }],
    media: [],
  },
  {
    slug: 'arabica-coffee',
    scientificName: 'Coffea arabica',
    commonName: 'Arabica coffee',
    category: 'coffee',
    growthPace: 'moderate',
    heightTimeline: [{ years: 1, height_m: 0.5 }, { years: 3, height_m: 1.8 }, { years: 6, height_m: 3 }],
    canopyNotes: 'Compact shrub for the highlands (Mt Elgon, Rwenzori, West Nile hills); first crop after about 3 years.',
    rootNotes: 'Needs deep, well-drained soil; grows best under light shade trees such as Grevillea.',
    ecologicalZones: [HIGHLAND],
    localNames: [],
    media: [],
  },

  // ── Cocoa ────────────────────────────────────────────────
  {
    slug: 'cocoa',
    scientificName: 'Theobroma cacao',
    commonName: 'Cocoa',
    category: 'cocoa',
    growthPace: 'moderate',
    heightTimeline: [{ years: 1, height_m: 0.8 }, { years: 3, height_m: 2.5 }, { years: 8, height_m: 5 }],
    canopyNotes: 'Small understorey tree; pods grow on the trunk from about year 3. Plant 3 m apart under banana or shade trees.',
    rootNotes: 'Taproot with shallow feeder roots; needs moist, well-drained soil and shelter from wind.',
    ecologicalZones: [MOIST, LAKE, WETLAND],
    localNames: [],
    media: [],
  },
];
